chutney CI: set CHUTNEY_ARTI before configuring chutney network
This is needed to support chutney networks containing arti nodes.

diff --git a/tests/chutney/setup b/tests/chutney/setup
--- a/tests/chutney/setup
+++ b/tests/chutney/setup
@@ -84,6 +84,22 @@ echo "export CHUTNEY_BIN=\"$CHUTNEY_BIN\"" >> tests/chutney/arti.run
 export CHUTNEY_DATA_DIR="${CHUTNEY_DATA_DIR:-$(pwd)}"
 echo "export CHUTNEY_DATA_DIR=\"$CHUTNEY_DATA_DIR\"" >> tests/chutney/arti.run
 
+# It's not really possible to know where the user built the arti binary.
+# Was it a debug build, a release build, did they use '--target <triple>', etc?
+# Try the platform triple build directory first, and then the usual build directory.
+# It's possible we may choose a stale binary, but there's not much else we can
+# do here other than maybe comparing timestamps.
+if [ -x ./target/x86_64-unknown-linux-gnu/debug/arti ]; then
+	CHUTNEY_ARTI=./target/x86_64-unknown-linux-gnu/debug/arti
+elif [ -x ./target/debug/arti ]; then
+	CHUTNEY_ARTI=./target/debug/arti
+else
+	echo "Could not find a debug arti binary. You can build it with 'cargo build -p arti'."
+	exit 1
+fi
+export CHUTNEY_ARTI
+echo "export CHUTNEY_ARTI=\"$CHUTNEY_ARTI\"" >> tests/chutney/arti.run
+
 "${CHUTNEY_BIN}" configure "$target"
 "${CHUTNEY_BIN}" start "$target"
 CHUTNEY_START_TIME=180 "${CHUTNEY_BIN}" wait_for_bootstrap "$target"
@@ -100,23 +116,9 @@ if [ "$(id -u)" = "0" ] ; then
     ARTI_FLAGS+=("-o" "application.allow_running_as_root=true")
 fi
 
-# It's not really possible to know where the user built the arti binary.
-# Was it a debug build, a release build, did they use '--target <triple>', etc?
-# Try the platform triple build directory first, and then the usual build directory.
-# It's possible we may choose a stale binary, but there's not much else we can
-# do here other than maybe comparing timestamps.
-if [ -x ./target/x86_64-unknown-linux-gnu/debug/arti ]; then
-	cmd=./target/x86_64-unknown-linux-gnu/debug/arti
-elif [ -x ./target/debug/arti ]; then
-	cmd=./target/debug/arti
-else
-	echo "Could not find a debug arti binary. You can build it with 'cargo build -p arti'."
-	exit 1
-fi
-
 (
 	set +e
-	"$cmd" proxy -c "${CHUTNEY_DATA_DIR}/nodes/arti.toml" -d 35353 \
+	"$CHUTNEY_ARTI" proxy -c "${CHUTNEY_DATA_DIR}/nodes/arti.toml" -d 35353 \
 	       "${ARTI_FLAGS[@]}" &
 	arti_pid=$!
 	echo "pid=$arti_pid" >> tests/chutney/arti.run
