shadow CI: fail on arti logged errors

diff --git a/tests/shadow/run b/tests/shadow/run
--- a/tests/shadow/run
+++ b/tests/shadow/run
@@ -46,6 +46,15 @@ if [ -n "$nonempty_stderr" ]; then
   exit 1
 fi
 
+# Look for errors in arti logs.
+# TODO: Maybe fail on warnings, too? There currently are a few, though.
+arti_errs=$(find shadow.data/hosts/ -name 'arti*.stdout' -exec grep --with-filename '\bERROR\b' \{\} \;)
+if [ -n "$arti_errs" ]; then
+  echo "Found arti errors:"
+  echo "$arti_errs"
+  exit 1
+fi
+
 HOSTS=(
   articlient-onion
   articlient-onion-auth
