ci: Fix variable not expanding.

diff --git a/tests/shadow/run b/tests/shadow/run
--- a/tests/shadow/run
+++ b/tests/shadow/run
@@ -72,16 +72,17 @@ HOSTS=(
 )
 
 for HOST in "${HOSTS[@]}"; do
-  file="shadow.data/hosts/$HOST/arti*.stdout"
+  # There should be only one such file per host.
+  file=(shadow.data/hosts/"$HOST"/arti*.stdout)
   # TODO: this is a temporary measure until we implement other ways of testing
   # that the circuits we've built have the desired properties.
-  bugs="$(grep -c Bug "$file" || true)"
+  bugs="$(grep -c Bug "${file[*]}" || true)"
 
   if [ "$bugs" -eq 0 ]
   then
     echo "Simulation successful"
   else
-    echo "Failed. Found $bugs internal errors in $file."
+    echo "Failed. Found $bugs internal errors in ${file[*]}."
     exit 1
   fi
 done
